# fly.toml file generated for jphenow-tailscale on 2023-04-14T16:48:41-05:00

app = "jphenow-tailscale"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ord"

[build]
image = "tailscale/tailscale"

[processes]
# work around their busted container
app = "sh -c \"export PATH=$PATH:/usr/local/bin; containerboot\""

[env]
# TS_AUTHKEY set via secret
# TS_EXTRA_ARGS = "--advertise-tags tag:flyio" # not allowed (maybe due to free tier)
TS_HOSTNAME = "jphenow-flyio"
TS_ROUTES = "fdaa::3/128,fdaa:0:2b6::/48"
